### ISSUE TITLE
 Messages not received by application (Callback function not called for the event but websockets frames are received on the network )

### ISSUE THREAD

**Issue by Prinkesh** [probil/vue-socket.io-extended#105]
```
sockets: {
    connect: function() {
      console.log("connected");
    },
    "myResponse": function(message) {
      console.log("message recv", message);
      // if message length is more than 17000 bytes this callback stop getting called , however i can see the websocket frames being received in chrome devtools 
      // When i keep decreasing the message length this events are fired but it increase overall latency of the application 
  }
}
```

**Comment by giodegio** [comment]
I had the same problem, and the solution is to initialize VueSocketio in the following way:
(a little bit different from the original VueSocketio library)

  Vue.use(VueSocketio, SocketInstance, {store}); // ==> the third parameter "options" is an object!

As you can see in src/Main.js, line 12, the options are passed to the observer object:
const observer = new Observer(socket, options);

Then look at src/Observer.js, line 16:
constructor(connection, { store, ...customOptions } = {}) {
...
}

NOTE: I've checked, and this particularity is also documented: 
see "Usage", in "Vuex Store integration" section.

bye!

**Comment by probil** [comment]
@Prinkesh thanks for your issue.
I will try to reproduce it locally and will respond you soon. :)

**Comment by Prinkesh** [comment]
My bad there was some issue with the data i was sending to the client some of the json key value was `nan` . With bunched packets the probability of a frame having such values increased and the socket-io lib was unable to parse the message hence no data was seen by client

**Comment by probil** [comment]
Ok. Thanks for your response. Let me know if you have any other issues. Have a nice day :)
