### ISSUE TITLE
Use with a reverse proxy

### ISSUE THREAD

**Issue by ezimmert** [probil/vue-socket.io-extended#106]
I try to use vue-socket.io-extended behind a nginx reverse proxy but I always end with a 502 error.
With socket.io I used the "path" option. Is it also available on vue-socket.io-extended ?
For instance: `Vue.use(VueSocketIO, io('http://192.168.1.1', {path: '/ws'}), { store })`

Thanks for your help

**Comment by probil** [comment]
Hi, @ezimmert 
Thanks for your issue.
Yes,`path` is also available here. You can pass any available options to socket.io constructor. Full list of such options you can find [here](https://socket.io/docs/client-api/). E.g. this should work:

```js
import VueSocketio from 'vue-socket.io-extended';
import io from 'socket.io-client';
import store from './store'

Vue.use(VueSocketio, io('http://192.168.1.1', { path: '/ws' }), { store });
```
Also you can use it this way so it feels close to official socket.io docs:
```js
import VueSocketio from 'vue-socket.io-extended';
import io from 'socket.io-client';
import store from './store'

const socket = io('http://192.168.1.1', {
  path: '/ws'
});

Vue.use(VueSocketio, socket, { store });
```

Probably something wrong with nginx configuration :thinking: 
Let me know if you have any additional questions

**Comment by probil** [comment]
Closed due to inactivity.
