### ISSUE TITLE
Client could not reach server in production

### ISSUE THREAD

**Issue by harishankards** [probil/vue-socket.io-extended#108]
Hey @probil,
Hope you are doing good.

This is my code which helped me to run the app locally: https://github.com/probil/vue-socket.io-extended/issues/67#issuecomment-390113821
When I have successfully deployed to the server, I changed the URL from `localhost:3000` to `mydomain.com`, it throws an error as below. What should I do more?

`GET http://localhost:3000/socket.io/?EIO=3&transport=polling&t=MHV7jPy 0 ()` 

![image](https://user-images.githubusercontent.com/5006693/42206224-2259d284-7ec4-11e8-87d7-095d75c32fca.png)

**Comment by probil** [comment]
Hey @harishankards 
Nice to see you again :)

It seems like you have to change this line as well:
```diff
- Vue.use(VueSocketio, io('http://localhost:3000'))
+ Vue.use(VueSocketio, io('http://mydomain.com:3000'))
```
Also, make sure server deployed correctly to the domain, don't forget to open port 3000 to the world or setup port redirection

**Comment by harishankards** [comment]
@probil :) 

Thanks for the response. It was my mistake, later I noticed that I gave the wrong domain. Still I dint give like `Vue.use(VueSocketio, io('http://mydomain.com:3000'))`. I didn't mention the port. But it's connected, as it says via console.

But after it's connected, it's throwing this error:
```js
websocket.js:112 WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=3&transport=websocket&sid=ilRkoEQ4tAihcx3TAAAJ' failed: Error during WebSocket handshake: Unexpected response code: 400
r.doOpen @ websocket.js:112
```

**Comment by probil** [comment]
Could you please provide whole listing of your files server + client?

**Comment by harishankards** [comment]
By `whole listing of your files`, do you mean the list of names of files in a hierarchial structure?

**Comment by probil** [comment]
There is status 400, it means an error. So it's not actually connected.
```
400 - Bad Request
```
By 'whole listing of your files' I mean the whole code that can help figure out an issue. 
In any case, the issue clearly lies in the server/socket.io configuration and your understanding of how both works.

I think we should continue this discussion in Gitter

**Comment by harishankards** [comment]
cool buddy. We will continue the discussion there!
