### ISSUE TITLE
The message is not received, when server emitted

### ISSUE THREAD

**Issue by settenke** [probil/vue-socket.io-extended#110]
Hi!

My problem is:
I have a Vuex application with store and i have a simple socketio server.
If the server receives a message, it will broadcast it. The server logs that this has happened, the client does not received it.

SERVER:
```js
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

io.on('connection', function(socket) {
  console.log(`Client connected [id=${socket.id}]`);

  socket.on('server_message', function(data) {
    console.log(`server_message: `, JSON.stringify(data));
    socket.emit('server_message', { msg: data.msg });
  });

  socket.on('disconnect', function() {
    console.log(`Client disconnected [id=${socket.id}]`);
  });
});

http.listen(3000, function(){
  console.log('listening on *:3000');
});
```

FRONTEND:

main.js
```js
import Vue from 'vue';
import App from './App.vue';
import socketio from 'socket.io-client';
import VueSocketIO from 'vue-socket.io-extended';
import store from './store';

Vue.use(VueSocketIO, socketio('http://localhost:3000', {
            store: store,
            format: 'json',
            reconnection: true, // (Boolean) whether to reconnect automatically (false)
            reconnectionAttempts: 5, // (Number) number of reconnection attempts before giving up (Infinity),
            reconnectionDelay: 3000, // (Number) how long to initially wait before attempting a new (1000)
        }), store);

new Vue({
    store,
    render: h => h(App)
}).$mount('#app');
```

store/index.js
```js
import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

export default new Vuex.Store({
    state: {
        isConnected: false,
        message: '',
        reconnectError: false,
        event: null,
        count: 0,
        serverMessage: ''
    },
    mutations: {
        SOCKET_CONNECT(state) {
            state.reconnectError = false;
            state.isConnected = true;
            state.event = 'connected';
            state.serverMessage = 'socket connected';
        },
        SOCKET_ERROR (state)  {
            state.isConnected = false;
            state.event = 'error';
            state.serverMessage = 'socket error';
        },
        SOCKET_DISCONNECT(state) {
            state.isConnected = false;
            state.reconnectError = false;
            state.event = 'disconnect';
            state.serverMessage = 'socket disconnect';
        },
        SOCKET_RECONNECT(state) {
            state.reconnectError = false;
            state.serverMessage = 'socket reconnect';
        },
        SOCKET_RECONNECT_ERROR(state) {
            state.reconnectError = true;
            state.serverMessage = 'socket reconnect error';
        },
        SOCKET_RECONNECT_ATTEMPT(state) {
            state.reconnectError = true;
            state.count = state.count + 1 ;
            state.serverMessage = 'socket reconnect error';
        },
        SOCKET_CONNECT_ERROR (state)  {
            state.isConnected = false;
            state.event = 'connect error';
            state.serverMessage = 'socket connect error';
        },
        
        SOCKET_SERVER_MESSAGE (state, message)  {
            console.log(message);
            state.message = message;
            state.serverMessage = 'message received';
        },
    },
    actions: {
        socket_serverMessage: function(message) {
             console.log(message);
        }
    }
});
```

+1 event listener in a component:
```js
this.$options.sockets.server_message = (data) => console.log(data);
```

What could be the problem?
THX!

**Comment by probil** [comment]
Hi, @settenke Thanks for your issue. I will investigate your code and will respond you soon :)

**Comment by settenke** [comment]
Hi @probil !
Thanks for the quick response! There is so much information that it is running a socket.io server in a docker container. Although this in principle does not matter... From another container, the tooth is the answer and you emit it (docker compose). First, the Vuex app was in a docker container, but because of the sockjs connection error (trying connect the public network ip and --host parameter is not worked), I tried it directly. Because that was my first suspicion. Finally he did not come in.

bye

**Comment by probil** [comment]
Hi again, @settenke 

I've found the issue. You are using old syntax for store registration from v2.X but you are using v3 of the library. Please, check [release note for v3](https://github.com/probil/vue-socket.io-extended/releases/tag/v3.0.0)

In short, you need to add brackets:

```diff
Vue.use(VueSocketIO, socketio('http://localhost:3000', {
            store: store,
            format: 'json',
            reconnection: true, // (Boolean) whether to reconnect automatically (false)
            reconnectionAttempts: 5, // (Number) number of reconnection attempts before giving up (Infinity),
            reconnectionDelay: 3000, // (Number) how long to initially wait before attempting a new (1000)
-        }), store);
+        }), { store });
```

**Comment by probil** [comment]
Also I have [working example here](https://fex.net/153486487299?fileId=580602992), both dynamic listener and store mutations are executed on server event

1) extract archive
2) run `npm install` in the root folder
3) run `npm i` in the `<root>/client` folder
4) run `npm run start` in the root folder to start the server
5) run `npm run serve` in the `<root>/client` folder to serve vue app
6) Open the browser, press the button, and check the console

**Comment by probil** [comment]
Let me know if you have any other issues @settenke . Have a great day :wave:

**Comment by settenke** [comment]
Dear @probil !
Unfortunately, something is still not good. If another browser sends the message, the socket server will accept it, but it will not arrive to the first browser.
My data flow plan:

```Backend server -> [msg] -> Socket server -> [msg] -> Browser```

Thx

**Comment by settenke** [comment]
Dear @probil !
I found the fault. I use wrong emitting method, if I will be changed to broadcasting, its working...

SocketServer
```
-socket.emit('server_message', data);-
socket.broadcast.emit('server_message', data);
```

Sorry, my fault

**Comment by probil** [comment]
Thanks for update @settenke 
So, problem is solved, right? I'd like to close the issue

**Comment by kamalptw** [comment]
@probil After a few hours of searching I was able to solve this using the {store} syntax you suggested.
Thank you
