### ISSUE TITLE
How to use "sockets" property?

### ISSUE THREAD

**Issue by KonstantinKudelko** [probil/vue-socket.io-extended#112]
@probil thx for extension version for VueSocket.io and great support!
I want to know how `sockets` property really works?

I use library like that for handle events:
`this.$socket.on(event, data => {})`

I think like `sockets` property do the same, my event is dynamic variable and depends on `id`

How I can use `sockets` property in that case?

**Comment by probil** [comment]
Hi, @KonstantinKudelko 
Thanks for your question. 

#### You can use dynamic socket listeners for that
```js
new Vue({
  mounted() {
    const event = someMagicCalculations(); // `event` is generated here dynamically based on id
    // now we can define our socket listeners
    this.$options.sockets[event] = data => {
       // handler implementation here
    }
  },
});
```

Probably you'd need to destroy listener (to prevent memory leaks, etc) in this case you need to store calculated event name somewhere. There simplest way is to put it inside `computed` property, as alternative you can store it in `data` as well:

```js
new Vue({
  data: () => ({
     id: 15, // just a placeholder for your id
  }),
  computed: {
    computedEventName () {
      return `user-${this.id}`;
    }
  },
  mounted() {
    this.$options.sockets[this.computedEventName] = data => {
      // handler implementation here
    }
  },
  beforeDestroy() {
    delete this.$options.sockets[this.computedEventName];
  },
});
```
FYI: I don't know your particular case but I don't think socket events with `id` inside is a good idea. Probably you need to use alternative approach like _rooms_ or _send events to particular client_ on the server so events are delivered to correct client.

**Comment by KonstantinKudelko** [comment]
Thx, for your help, for example I have two `$socket` handlers in our file to listen different events, and every time I need to check if socket not undefined, so my question how I can avoid that?

```
if (this.$socket) {
  //magic
}
```
how I can do that in one place?

**Comment by probil** [comment]
I don't understand why you need to check is `this.$socket` is defined.
Maybe you can show some part of your code so it will be easier for me to help you?

**Comment by KonstantinKudelko** [comment]
Yeah, for example:

In main vue instance I have statement for install vue-socket-io:

```
import VueSocketio from 'vue-socket.io'
import socketio from 'socket.io-client'

Vue.use(VueSocketio, socketio(r.data.notify_url, { path: '/api/socket' }))
```

And I have file components `.vue`, and there I use `this.$socket` variable to access my sockets, and there I need to do check statement if we have this sockets like:

```
if (this.$socket) {
  //do stuff with socket
}
```

and that statement I have multiple times, so how I can do check statement more generic?

thx

**Comment by KonstantinKudelko** [comment]
Yes, as far as I understand I need to check whether the socket connection, so I do the checking

**Comment by probil** [comment]
No, you don't have to.
You can define socket.io listeners even though there is no connection right now (unlike when you use socket.io client directly). It will work because events are not actually attached to the socket.io client directly. This plugin uses only one event interceptor that behaves like a spy. When an event is fired by the server, the plugin takes event data from spy and calls all registered functions (mutations/actions/component functions under "sockets") associated with it.

FYI: if you need to check if the connection is actually established you need to check `this.$socket.connected` instead.

I hope this will help you.

**Comment by KonstantinKudelko** [comment]
Thx, so much
