### ISSUE TITLE
How to prevent connection until authed?

### ISSUE THREAD

**Issue by busheezy** [probil/vue-socket.io-extended#114]
I have a home page where I'm not using sockets at all. I'm using this with Vuex. Is there a way to prevent the socket from trying to connect on my home page or until it at least has the auth info in my store? There might be something obvious, it's late.

**Comment by busheezy** [comment]
I was tired. I just disabled auto connections and connected the sockets manually.

**Comment by busheezy** [comment]
Thanks for everything.

**Comment by probil** [comment]
Yeah, I think it's a good idea, @ALiangLiang 
Thanks

**Comment by xuejiangjun** [comment]
> Hi, @busheezy Thanks for your issue :)
> You are right. You should disable auto connection and connect to socket later (only on correct page, when auth info is in the store, etc)
> 
> ```js
> import VueSocketio from 'vue-socket.io-extended';
> import io from 'socket.io-client';
> 
> const socket = io({
>   url: 'http://socketserver.com:1923',
>   autoConnect: false
> });
> 
> Vue.use(VueSocketio, socket);
> 
> // when everything is ready to connection (correct page, auth info in store, etc)
> socket.open();
> // or in components
> this.$socket.open();
> ```
> 
> more info in official socket.io documentation
> https://socket.io/docs/client-api/#socket-open
> 
> Let me know is the issue still relevant

I use options like this
> const socket = io('http://socketserver.com:1923', {
>   autoConnect: false
> });
not 
> const socket = io({
>   url: 'http://socketserver.com:1923',
>   autoConnect: false
> });
documentation https://socket.io/docs/client-api/#io-url-options
sorry my English not good

**Comment by LaKing** [comment]
@xuejiangjun is right.

Only the options should be in curly braces.

**Comment by probil** [comment]
Updated original answer. Thanks @xuejiangjun for notice and @LaKing for check.
Added to [FAQ](https://github.com/probil/vue-socket.io-extended#question-faq)

**Comment by mornir** [comment]
In my case, this works:
```js
const socket = io({
   url: 'http://socketserver.com:1923',
   autoConnect: false
});
```
And this doesn't:
```js
const socket = io('http://socketserver.com:1923', {
   autoConnect: false
});
```
@probil In the article you referenced, the autoConnect property is indeed passed as the first argument: https://socket.io/docs/client-api/#socket-open

**Comment by salsa2k** [comment]
Try:
      this.$socket.io.opts.query = {
        token: 'your-token-here'
      };

     this.$socket.open();

**Comment by dedosmedia** [comment]
> Hi, @busheezy Thanks for your issue :)
> You are right. You should disable auto connection and connect to socket later (only on correct page, when auth info is in the store, etc)
> 
> ```js
> import VueSocketio from 'vue-socket.io-extended';
> import io from 'socket.io-client';
> 
> const socket = io('http://socketserver.com:1923', {
>   autoConnect: false
> });
> 
> Vue.use(VueSocketio, socket);
> 
> // when everything is ready to connection (correct page, auth info in store, etc)
> socket.open();
> // or in components
> this.$socket.open();
> ```
> 
> more info in official socket.io documentation
> https://socket.io/docs/client-api/#socket-open
> 
> Let me know is the issue still relevant

with autoConnect = false 
this.$socket.open()  did no worked for me. 
I had to use this.$socket.client.open()    
Has something changed over the last months or am I doing something wrong?

**Comment by Nicholaiii** [comment]
If you use jwt, with [socketio-jwt](https://github.com/auth0-community/auth0-socketio-jwt) you can just connect like normal and emit `authenticate` when ready. No work-arounds neccessary.

**Comment by longyanjiang** [comment]
> 嗨，@busheezy 谢谢你的问题 :) 你是对的。您应该禁用自动连接并稍后连接到套接字（仅在正确的页面上，当身份验证信息在商店等时）
> 
> ```js
>  从'vue-socket.io-extended'导入VueSocketio  ；从'socket.io-client'导入io ； 
>    
> 
> const  socket  =  io ( 'http://socketserver.com:1923' ,  { 
>   autoConnect : false 
> } ) ;
> 
> 视图。使用（VueSocketio ， 套接字）；
> 
> // 当一切准备好连接时（正确的页面，商店中的身份验证信息等）
> socket . 打开( ) ; 
> // 或在组件中
> this . $socket 。客户。打开( ) ;  // 或 `this.$socket.open()` 库版本 1.x-3.x
> ```
> 
> 官方 socket.io 文档中的更多信息 https://socket.io/docs/client-api/#socket-open
> 
> 让我知道这个问题是否仍然相关

What if you can't get the token in the initialization phase using nuxt? When the login is successful, you can't put the token in the parameters of the IO connection

**Comment by longyanjiang** [comment]
> 嗨，@busheezy 谢谢你的问题 :) 你是对的。您应该禁用自动连接并稍后连接到套接字（仅在正确的页面上，当身份验证信息在商店等时）
> 
> ```js
>  从'vue-socket.io-extended'导入VueSocketio  ；从'socket.io-client'导入io ； 
>    
> 
> const  socket  =  io ( 'http://socketserver.com:1923' ,  { 
>   autoConnect : false 
> } ) ;
> 
> 视图。使用（VueSocketio ， 套接字）；
> 
> // 当一切准备好连接时（正确的页面，商店中的身份验证信息等）
> socket . 打开( ) ; 
> // 或在组件中
> this . $socket 。客户。打开( ) ;  // 或 `this.$socket.open()` 库版本 1.x-3.x
> ```
> 
> 官方 socket.io 文档中的更多信息 https://socket.io/docs/client-api/#socket-open
> 
> 让我知道这个问题是否仍然相关

What if you can't get the token in the initialization phase using nuxt? When the login is successful, you can't put the token in the parameters of the IO connection
