### ISSUE TITLE
Data does not flow through the web socket until I refresh the page

### ISSUE THREAD

**Issue by SamuelTremain** [probil/vue-socket.io-extended#186]
I don't think this is a bug with vue-socket.io-extended, but I wanted to post this question in case someone has run into a similar problem and can possibly help me.

I am trying to use web sockets with a chart that displays live time series data. The chart posts a new data point every second and I have logs that display the information for each data point in both the server-side terminal and the browser console. I am using the component configuration (i.e., no Vuex integration) because I only need a web socket connection on the page with the chart.

When I start the app, a message gets logged to the terminal showing that a web socket connection was made with the server. (Actually, three messages get logged each time I start my app and each message shows a different socket ID. I don't know why that is.) No other logs get printed to the terminal. Then when I navigate to the page that contains the chart, I expect there to be logs printed for each new data point, but no logs are printed in either the terminal or the browser console. However, while still on the page with the chart, if I refresh the browser, then the data starts coming through in the terminal and the browser console and the chart even gets populated with the correct data points.

Has anyone had a similar experience or does anyone know why the data does not flow into my app until after I refresh the page that has both the socket configuration and the chart where the data is displayed?

I am using hapi.js as my Node server, in case that helps.

**Comment by probil** [comment]
@SamuelTremain 
Interesting. Could you please provide minimal reproducible example? I'd like to take a look. I'm not sure someone will help you without some actual code.

**Comment by SamuelTremain** [comment]
@probil 
I found a solution. If I run into more problems I will let you know. Thank you for responding.
