### ISSUE TITLE
How To Send Auth Token In every request?

### ISSUE THREAD

**Issue by takielias** [probil/vue-socket.io-extended#188]
I want to use JWT token for Authentication. Actually I'm looking for [this](https://github.com/MetinSeylan/Vue-Socket.io/issues/65). Is there any way of getting this?

**Comment by probil** [comment]
@takielias There is 2 ways how you can achieve that
1) Put it into the connection query or header as described [on stackoverflow](https://stackoverflow.com/questions/36788831/authenticating-socket-io-connections) or [on the link you have provided](https://github.com/MetinSeylan/Vue-Socket.io/issues/65#issuecomment-310886128). In this case server will prevent non-authenticated connection. It's generally OK but have some drawbacks.
2) Skip validation on connection and authenticate later using socket.io events. This one is more complex but covers more cases. There is a server module for that called [`socketio-jwt`](https://github.com/auth0-community/socketio-jwt). Any way you have to use option (1) for token invalidation.

**Comment by rstormsf** [comment]
@probil 
here is the problem I'm facing.

server:
```js
function main(serverToBind, dbConnection, options) {
  const io = socketio(serverToBind, options)
  io.use((socket, next) => {
    console.log('io.use', socket.handshake.query) // EMPTY! :-(
    next()
  })
  io.of(/^\/netId-\d{1,9}$/, onConnection({dbConnection, io}))
  return io
}
function onConnection({ dbConnection, io }) {
  return (socket) => {
    console.log('onConnection', socket.handshake.query) // NOT EMPTY :-)
}}
```

client side:

```
import io from 'socket.io-client';

const SOCKETIO_URL = process.env.VUE_APP_SOCKETIO_URL
const socket = io(SOCKETIO_URL, {
  transports: ['websocket'],
  autoConnect: false
})

export default socket

//main.js

import Vue from 'vue'
import $socket from './socket-instance'
Vue.use(VueSocketio, $socket, { store })

//vuex-store

connect ({rootState, state}) {
    this._vm.$socket.query = `roman=${123}&`
    if(netId){
      this._vm.$socket.query += `&netId=${netId}&`
    }
     return this._vm.$socket.open();
    }
  },
```

why the handshake is not visible in middleware, only `on connection` hook?

**Comment by rstormsf** [comment]
Problem solved!!!

clientSide:
USE `this._vm.$socket.io.opts.query`  vs `this._vm.$socket.query`
this._vm.$socket.io.opts.query.netId = netId

**Comment by elC0mpa** [comment]
Hi @probil, I am trying to achieve something like this:

- I want to connect to the the server using this URL: 
  - https://socket.treve.app/client/1?token=myToken
- I tried to solve it by doing this:
  - this.$socket.client.io.opts.query = {
      token: this.$store.getters['auth/token']
    };

This approach doesn't work, any idea?
