### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by barrymckay397** [probil/vue-socket.io-extended#253]
There is an issue with the latest version (v3.2.0) in IE11. It seems as though the 'camelcase' module is no longer being transpiled correctly to ES5 (I'm seeing usages of 'fat arrows'). The previous version (v3.1.0) seems to be working just fine.

Thanks in advance!

**Comment by probil** [comment]
Hi, @barrymckay397 
Thanks for your issue and investigation. I will take a look soon

**Comment by probil** [comment]
Fixed in `v3.2.1`
Thanks @barrymckay397
