### ISSUE TITLE
Server Address via user input

### ISSUE THREAD

**Issue by theskyliner** [probil/vue-socket.io-extended#258]
Hey there,

I want to develop a client in vue, where the user can input the server's address. So the server address is not available when vue is initialized. Is this even possible?

Thanks in advance!
Nick

**Comment by probil** [comment]
@theskyliner You should investigate how to do it without `vue-socket.io-extended`
It's not supported by the library right now

**Comment by colinbes** [comment]
Still in testing phase but this appears to work with address not being known at time of initialization.

What I did in setup stage is set socket uri to empty string ‘’ and autoConnect to false. Then when user enters url string I use this.$socket.client.io.uri to user supplied host address and then call this.$socket.client.open().

I am typing this from memory so please excuse minor mistakes but should give idea on (what appears as a) working solution,
