### ISSUE TITLE
Connection in the local network

### ISSUE THREAD

**Issue by ll931217** [probil/vue-socket.io-extended#261]
Hello @probil,

I am wondering if I wrote this incorrectly but I can't get the socket to connect to my server. My server address is `http://0.0.0.0:3000` and this is the `socket.io.js` code I have:

    import Vue from 'vue'
    import io from 'socket.io-client'
    import VueSocketIO from 'vue-socket.io-extended'
 
    export default ({ store }) => {
      Vue.use(VueSocketIO, io("http://0.0.0.0:3000"), { store })
    }

**Comment by probil** [comment]
Hi @ll931217 
Yes it should work. You can try `localhost` or `127.0.0.1`

**Comment by ll931217** [comment]
Hey @probil 
I did try localhost, it doesn't connect to my server on the local network, only if I typed in the IP `192.168.0.217:3000` works.

**Comment by codebender828** [comment]
You could also try using `window.location.origin`. As in
```javascript
export default ({ store }) => {
  Vue.use(VueSocketIO, io(window.location.origin), { store })
}
```

**Comment by probil** [comment]
@ll931217 `localhost` or `0.0.0.0` works only when server is on the same machine. Otherwise you should use server's IP or dns name
