### ISSUE TITLE
Clarification of README

### ISSUE THREAD

**Issue by douira** [probil/vue-socket.io-extended#295]
I think in the [README documentation](https://github.com/probil/vue-socket.io-extended#gear-configuration), it should be "_Prepend to event name while converting event to action._" instead of "_Append to event name while converting event to action._" in order to make it clear that the prefixes are in fact put before the mutation/action names and not after.

**Comment by douira** [comment]
nice! thanks

**Comment by probil** [comment]
Thank you @douira
