### ISSUE TITLE
Vue-socket.io-extended with Typescript

### ISSUE THREAD

**Issue by S1mpler** [probil/vue-socket.io-extended#357]
I am using `vue-property-decorator` with typescript in my Vue application. 
The only thing i'm missing is `@Socket`decorator. It would be really great if we can implement it. I could do it, but I would need your help :) 

![image](https://user-images.githubusercontent.com/6653492/57982262-28f43000-7a43-11e9-814a-4213614cef18.png)

Слава Україні!

**Comment by probil** [comment]
Hi @S1mpler 

Great idea! Let's do it

I will be glad to help you to write `@Socket` decorator. 

You can check this tutorial. It looks really easy
https://egghead.io/lessons/vue-js-create-your-own-decorators-in-vue-with-typescript

the basic idea is following
```ts
import Component, { createDecorator } from 'vue-class-component'

const Socket = createDecorator((component: any, key: string) => {
  component.$options.sockets[key] = component[key];
  delete component[key];
})

@Component
export default class HelloWorld extends Vue {
  @Socket
  connect() {
    console.log('socket connected');
  }
}
```
I'm looking forward to check your PR ;)

---
Героям Слава! 🇺🇦

**Comment by Luluno01** [comment]
I don't have enough time for creating a PR but here is my working version:

```TypeScript
import { createDecorator } from 'vue-class-component'


/**
 * vue-socket.io-extended decorator
 */
export const Socket = createDecorator((option, key) => {
  option.sockets = option.sockets || {}
  option.sockets[key] = option.methods![key]
})

export default Socket

```

Note that the method being decorated should be retrieved via `option.methods`.

**Comment by probil** [comment]
@Luluno01 I will release it in the next version of the library. Thanks!

**Comment by xoxmaman** [comment]
I think the next should be better:
```js
import { createDecorator } from 'vue-class-component'
import { ComponentOptions } from 'vue'
import Vue from 'vue'
import string from 'string'

export const Meta = createDecorator((options: ComponentOptions<Vue>, key: string) => {
    options.metaInfo = options.methods && options.methods.hasOwnProperty(key) ? options.methods[key] : undefined
})


export const Socket = createDecorator((options: ComponentOptions<Vue>, key: string) => {
    options.sockets = options.sockets || {}
    if (!options.methods || !options.methods.hasOwnProperty(key)) {
        return
    }

    methodNameToVariousFormats(key).forEach((formattedKey: string): void => {
        options.sockets![formattedKey] = options.methods![key]
    })
    debugger
})

function methodNameToVariousFormats(methodName: string): string [] {
    return [
        string(methodName).slugify().s,
        string(methodName).camelize().s,
        string(methodName).underscore().s,
        string(methodName).underscore().replaceAll('_', '-').s,
    ]
}
```

**Comment by Luluno01** [comment]
> I think the next should be better:
> 
> ```js
> import { createDecorator } from 'vue-class-component'
> import { ComponentOptions } from 'vue'
> import Vue from 'vue'
> import string from 'string' //https://www.npmjs.com/package/string
> 
> 
> export const Socket = createDecorator((options: ComponentOptions<Vue>, key: string) => {
>     options.sockets = options.sockets || {}
>     if (!options.methods || !options.methods.hasOwnProperty(key)) {
>         return
>     }
> 
>     methodNameToVariousFormats(key).forEach((formattedKey: string): void => {
>         options.sockets![formattedKey] = options.methods![key]
>     })
> })
> 
> function methodNameToVariousFormats(methodName: string): string [] {
>     return [
>         string(methodName).slugify().s,
>         string(methodName).camelize().s,
>         string(methodName).underscore().s,
>         string(methodName).underscore().replaceAll('_', '-').s,
>     ]
> }
> ```

@xoxmaman Looks like your code includes some naming conversion schema and will “guess” the correct event name by listening to all suspicious events, right? How about just provide the users a decorator factory and let them designate the event name by themselves?

```TypeScript
import { createDecorator } from 'vue-class-component'
import { ComponentOptions } from 'vue'
import Vue from 'vue'
import string from 'string'  //https://www.npmjs.com/package/string


export enum Format {
  SLUGIFY: 'slugify',
  CAMELIZE: 'camelize',
  UNDERSCORE: 'underscore',
  HYPHEN: 'hyphen',
  /* Other supported format */
}

export function Socket(nameOrFormat?: string | (originName: string) => string, useBuiltInFormat: boolean = false) {
  return createDecorator((options: ComponentOptions<Vue>, key: string) => {
    options.sockets = options.sockets || {}
    if (!options.methods ||
      /* Will this condition break mixins and inherited classes? */
      !options.methods.hasOwnProperty(key)) {
      return
    }

    methodNameToVariousFormats(key).forEach((formattedKey: string): void => {
      /* Calculate event name */
      let name: string
      if (useBuiltInFormat) {
        if (typeof nameOrFormat!= 'string') throw new TypeError('Expected a format name')
        name = methodNameToVariousFormats(nameOrFormat as string)
      } else {
        switch (typeof nameOrFormat) {
          case 'string': name = nameOrFormat; break
          case 'function': name = nameOrFormat(key); break
          case 'undefined': name = key; break
          default: throw new TypeError('Expected an event name or a formatter function')
        }
      }
      options.sockets![name] = options.methods![key]
    })
  })
}

function methodNameToVariousFormats(methodName: string, format: Format): string {
  if (format == Format.HYPHEN) return string(methodName).underscore().replaceAll('_', '-').s
  else return string(methodName)[format]().s
}

/* Usage
@Component
class App extends Vue {
  @Socket()
  public data() {
    // 'data'
  }

  @Socket('destroy-the-world')
  public onDestroyTheWorld() {
    // 'destroy-the-world'
  }

  @Socket('hyphen', true)
  public restartGame() {
    // 'restart-game'?
  }

  @Socket(s => s.slice(2))
  public onExit() {
    // 'Exit'
  }
}
*/
```

It is bloating now ;P.

Not tested.

**Comment by xoxmaman** [comment]
cool

**Comment by probil** [comment]
Implemented in `v4`
