### ISSUE TITLE
How to access to reply from a component's "this.$socket.emit"

### ISSUE THREAD

**Issue by stratosgear** [probil/vue-socket.io-extended#369]
Let me start by apologizing because this is not a bug but more of a question first (let's see if it is bug later on)

According to the socket.io specs the socket.io server can reply with a response to an event triggered by the client.

In your socket.io-extended  examples you already demonstrate how a Vue component can trigger a socketio event:

```js
methods: {
    clickButton(val) {
      // this.$socket is `socket.io-client` instance
      this.$socket.emit('emit_method', val);
    }
  }
```

I'm not sure how I can capture that response from the server.  Can you point me in the right direction...?

**Comment by probil** [comment]
Hi @stratosgear 

Since `this.$socket` is `socket.io-client` instance you can do with it [whatever you want](https://socket.io/docs/client-api/). 
In your case, you can pass additional callback function to the `emit`:

```js
// client:
methods: {
    clickButton(val = 'tobi') {
      this.$socket.emit('ferret', val, (data) => {
        console.log(data); // data will be 'woot' (reply from the server)
      });
    }
  }

// server:
io.on('connection', (socket) => {
  socket.on('ferret', (name, fn) => {
    // `name='tobi'` here
    fn('woot');
  });
});
```
See docs here https://socket.io/docs/client-api/#socket-emit-eventName-%E2%80%A6args-ack

Have a nice day :smile_cat:

**Comment by stratosgear** [comment]
Hi @probil  you're the best.  No idea how I missed that from the socket.io docs.  These javascript callbacks always get me as their syntax is so completely weird.

Thanks, I'll be closing this now!
