### ISSUE TITLE
GET http://localhost:3000/socket.io/?... 404 (Not Found)

### ISSUE THREAD

**Issue by TakCastel** [probil/vue-socket.io-extended#405]
Hey i'm having some difficulties implementing this in my Nuxt application.

I followed the documentation as you can see below. 

The file socket.io.js inside plugins
```js
import Vue from 'vue'
import io from 'socket.io-client'
import VueSocketIO from 'vue-socket.io-extended'

export default ({ store }) => {
  Vue.use(VueSocketIO, io('http://localhost:3000'), { store })
}
```
Implementation in nuxt.config.js 

```js
plugins: [
   (...)
    {
      src: '~/plugins/socket.io.js',
      ssr: false // <-- this line is required
    }
  ],
```

And then I have a vue page like this : 

```vue
<template>
  <v-layout>
    <v-flex>
      <v-btn color="primary" @click="ping">
        ping
      </v-btn>
    </v-flex>
  </v-layout>
</template>

<script>
export default {
  sockets: {
    connect() {
      console.log('socket connected')
    },
    customEmit(val) {
      console.log('this method was fired by the socket server. eg: io.emit("customEmit", data)')
    }
  },
  methods: {
    ping() {
      console.log('socket emit event')
      this.$socket.emit('emit_method', this.text)
    },
  }
}
</script>
```
I keep having these messages in console : 

<img width="809" alt="Capture d’écran 2019-07-23 à 14 55 54" src="https://user-images.githubusercontent.com/11198968/61713967-0a1f5c00-ad5a-11e9-804b-d57fcfccd7fc.png">

Did I forget something ?

You can find a link to my branch here : https://github.com/TakCastel/crabi-front/tree/feature/chatroom

Thank you very much ! 😀

**Comment by probil** [comment]
HI @TakCastel 
Thanks for your issue.

I guess you need socket.io server actually running on port 3000.

Please check official example from Nuxt core team
https://github.com/nuxt/nuxt.js/tree/dev/examples/with-sockets
Especially file `server.js`
