### ISSUE TITLE
Add emit methods to documentation for vuex

### ISSUE THREAD

**Issue by capndave** [probil/vue-socket.io-extended#406]
I spent quite a while the other day figuring out how to emit an event from the client using vuex, and finally found the explanation [here](https://github.com/MetinSeylan/Vue-Socket.io/issues/85). Would you like me to add something about it to the readme?

**Comment by probil** [comment]
Hi @capndave :wave: 
Thanks for your message

It's already there https://github.com/probil/vue-socket.io-extended/issues/91#issuecomment-397232621

![Screenshot from 2019-07-28 23-26-37](https://user-images.githubusercontent.com/6773202/62012487-9d5bf580-b18f-11e9-9505-68ce211c542c.png)


But I think, yeah, it's not clear enough :thinking:

**Comment by capndave** [comment]
I may try update the docs and submit a pr, if you're not opposed

**Comment by probil** [comment]
@capndave I will be glad for any contribution. Thanks @capndave

**Comment by probil** [comment]
Closed because of inactivity. But a contribution is still welcome :wink:
