### ISSUE TITLE
Is it possible to send an OAUTH2 token during the socket connection?

### ISSUE THREAD

**Issue by FreddyCrugger** [probil/vue-socket.io-extended#409]
Hello,

Is there a way to send a token to the back end and either validate or invalidate the connection with your plugin?

Thank you.

**Comment by probil** [comment]
Hi, @FreddyCrugger 

This plugin does nothing related to connection validation. It just connects socket io client instance with Vue and Vuex.

You should investigate how to do what you need on using official socket.io client. Come back here if you have any issue regarding the plugin
