### ISSUE TITLE
How to reconnect when the WebSocket connection is lost?

### ISSUE THREAD

**Issue by FreddyCrugger** [probil/vue-socket.io-extended#411]
Hello,

In your doc I cannot see anything that refers to reconnect to the webSocket when the connection is lost.

Does it works like with the native websocket vue plugin?

```js
Vue.use(VueSocketio, io('wss://echo.websocket.org'), {
  reconnection: true, // (Boolean) whether to reconnect automatically (false)
  reconnectionAttempts: 5, // (Number) number of reconnection attempts before giving up (Infinity),
  reconnectionDelay: 3000, // (Number) how long to initially wait before attempting a new (1000),
store
})
```

Would this be correct?

Thank you.

**Comment by probil** [comment]
Hi @FreddyCrugger 
This library is just a bridge between socket.io and Vue. 

You should configure low level details on a socket.io instance (instead of plugin):

```js
import VueSocketio from 'vue-socket.io-extended';
import io from 'socket.io-client';

// here we create a new socket.io client instance (with options when needed)
const socket = io('http://socketserver.com:1923', {
  // you use any options form here https://socket.io/docs/client-api/#new-Manager-url-options
  reconnection: true,
  reconnectionAttempts: 5,
  reconnectionDelay: 3000,
})

// here we connect previously created socket.io instance with Vue and Vuex
Vue.use(VueSocketio, socket, { store });
```

BTW, socket.io supports automatic re-connection

**Comment by probil** [comment]
Let me know if it helps and if you have any other questions

**Comment by FreddyCrugger** [comment]
My apology, I could not reply earlier.
Thank you so much for your reply.

I will be using Vuex with modules on my project and I am a bit confused on the Vuex part in your example. I have always worked with Axios and Web Sockets are new to me.

You have an example on this page:
https://www.npmjs.com/package/vue-socket.io-extended


 that shows this code:

```
actions: {
    otherAction(context, type) {
      return true;
    },
    socket_userMessage({ commit, dispatch }, message) {
      dispatch('newMessage', message);
      commit('NEW_MESSAGE_RECEIVED', message);
      if (message.is_important) {
        dispatch('alertImportantMessage', message);
      }
      // ...
    },
```


Should it not be this instead
```
actions: {
  socket_userMessage ({ dispatch, commit }, message) {
    return dispatch('newMessage', message).then(() => {
      commit('NEW_MESSAGE_RECEIVED', message);
    })
  }
```

The part that I need to grasp based on your example is from a vue page to vuex modules.

ie: User A lands on page A, how to subscribe to a channel and listen/send the events from that page to a Vuex module?

As my pages my have a channel for latest news, another for old news and another for ads.

Your example shows the action:
```
  actions: {
    socket_chatMessage() {
      console.log('this action will be called');
    }
  },
```

The issue I have is that your example does not show how to listen/subscribe to a channel and listen or broadcast certain events from a vue page to a Vuex module, It would have been great to see a full example on your github page.


Finally my last question, what is the difference between using your plugin and using socket.io directly into a Vue/Vuex project? 


Thank you so much.

**Comment by probil** [comment]
Hi, @FreddyCrugger 
the example is correct but I think I need to add some comments to make it more clear

According your example you have something like this
```js
mutations: {
  NEW_MESSAGE_RECEIVED(state, message) {
    state.messages[message.id] = message;
  }
},
actions: {
  newMessage({ dispatch, commit }, message ) {
    return processMessage(message); // returns promise
  }
  socket_userMessage ({ dispatch, commit }, message) {
    return dispatch('newMessage', message).then(() => {
      commit('NEW_MESSAGE_RECEIVED', message);
    })
  }
}
```
But why you need this extra action? We can simplify that:
```js
mutations: {
  NEW_MESSAGE_RECEIVED(state, message) {
    state.messages[message.id] = message;
  }
},
actions: {
  socket_userMessage ({ dispatch, commit }, message) {
    return processMessage(message).then(() => {
      commit('NEW_MESSAGE_RECEIVED', message);
    })
  }
}
```
And if your method `processMessage` is sync. We can simplify it even more:
```js
mutations: {
  SOCKET_USER_MESAGE(state, message) {
    state.messages[message.id] = processMessage(message);
  }
},
```

**Comment by FreddyCrugger** [comment]
Thank you for the reply, example and for your time, wonderful!

**Comment by probil** [comment]
> Finally my last question, what is the difference between using your plugin and using socket.io directly into a Vue/Vuex project?

You can, but you will have a lot of boilerplate code like this:
```js
import socketIoClient from './socket-io-client.js';

new Vue({
  mounted() {
    this.$options.onUserMessage = (message) => {
       this.messages.push(message);
    });
    this.$options.onConnect = () => {
       this.connected = true;
    })
    socketIoClient.on('userMessage', this.$options.onUserMessage);
    socketIoClient.on('connect', this.$options.onConnect);
  },
  beforeDestroy() {
    socketIoClient.off('userMessage', this.$options.onUserMessage);
    socketIoClient.off('connect', this.$options.onConnect);
  }
})
```
It's tough to write it in all the components

For Vuex it's even harder: you need to do it for every action and mutation in vuex module. 

So in general it's much easier to work with.

**Comment by FreddyCrugger** [comment]
Thank you so much, I get it now, you have really answered all my doubts about Vue and web sockets.
Great great explanations!
