### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Slluxx** [probil/vue-socket.io-extended#415]
Hey,
my main.js looks like this (application runs on :8081)

```js
import Vue from 'vue'
import App from './App'
import router from './router'
import BootstrapVue from 'bootstrap-vue'
import VueSocketIOExt from 'vue-socket.io-extended'
import io from 'socket.io-client'

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
import '@fortawesome/fontawesome-free/css/all.css'

const socket = io('http://localhost:1923')

Vue.use(BootstrapVue)
Vue.use(VueSocketIOExt, socket)
```

My browser console prints this:

`GET http://localhost:1923/socket.io/?EIO=3&transport=polling&t=Mo_18KQ net::ERR_CONNECTION_REFUSED`

Do i need to do something else or is it a bug?

**Comment by probil** [comment]
Hi @Slluxx 👋 
Are you sure you have socket.io server up and running on port `1923`?

**Comment by Slluxx** [comment]
Hey,

well, i didnt do anything else apart from whats in the readme. Would you mind telling me what else i have to do?

**Comment by capndave** [comment]
You'll need to write a basic API with Node/Express and Socket.IO if you haven't already. The [Socket.IO documentation](https://socket.io/docs/) is pretty good and tells you how to do it, and there are a few other tutorials up online.

**Comment by probil** [comment]
@capndave Sounds like we should add a mention about socket.io server to the docs

**Comment by capndave** [comment]
Sounds good!

*David Thompson*
Software Engineer
Travis Central Appraisal District
(512) 375-9134

**Comment by Slluxx** [comment]
Hey,

i used socket.io in other projects without problems but i really have no clue how to integrate it in vue. When trying the express "way" i am getting errors like `Critical dependency: the request of a dependency is an expression` which i dont know how to solve.

Or do i need a seperate project which just serves as socket server?

**Comment by Slluxx** [comment]
@capndave Well, i posted my code above and its in my Vue project. When trying to use it with express, i was just playing around with these lines.

```
var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io')(server);
```

But from your questions it seems like i need a separate express&socket node server that is not in the vue project. Is that correct?

I thought there is a simpler way but when i think about it, it's kind of clear. Vue builds static files and is not serving them via a server, right? I went under the assumption that it should work because of the `npm run dev` command which serves the files like a server.

**Comment by probil** [comment]
> But from your questions it seems like i need a separate express&socket node server that is not in the vue project. Is that correct?

Correct

@Slluxx you can connect vue project to express server, e.g. serve static files built by vue. 
But in practice I don't recommend doing. You will lose the HMR (during development) and possibility to deploy them separately. Having 2 projects separates responsibilities and reduces complexity in some way.

You can also use technique called _monorepo_ and have both of them in one git repo so it's easier to maintain.

**Comment by Slluxx** [comment]
I will try later today and keep you updated on my progress. Thanks :)
