### ISSUE TITLE
Event name is not recognized

### ISSUE THREAD

**Issue by ivokun** [probil/vue-socket.io-extended#43]
Hi Probil!

Thanks for forking this project. 
I try this and previous project (vue-socket.io) with vuex, but it's not working. `SOCKET_CONNECT` is working properly, but i can't trigger other event name such as `SOCKET_RESPONSE`

Any chance that i missing something?

Thanks!

**Comment by probil** [comment]
Hi, @ivokun 
Thanks for your attention to the project. 
Could you please provide some code (e.g how you define a listener, how you trigger an event)?
It will help me to find an issue much-much quicker.

**Comment by probil** [comment]
In any case, I will check it out

**Comment by ivokun** [comment]
Thanks for quick reply.
First i use vuex so i follow this one
`Vue.use(VueSocketio, io('http://socketserver.com:1923'), store);`

And listening data change with this one in store modules

`const mutations = {
  SOCKET_CONNECT: (state) => {
    state.isConnected = true
  },
  SOCKET_PUSH_NER_DATA: (state) => {
    state.response = 'test'
  }
}`

Actual event name is "push ner data", it's just listening to pushed data from server.
Or is it not support event name with space in it?

Sorry i can't explain it better. Let me know if you don't understand in some point.

**Comment by probil** [comment]
Btw, you have explained really good. Thanks :)

**Comment by ivokun** [comment]
Yeah, i check without space:

action:
`socket_pushNerData`

or

mutation
`SOCKET_PUSH_NER_DATA`

aren't trigger anything.

**Comment by probil** [comment]
@ivokun I'm going to investigate it deeply in the next 2-20 hours. I will let you know about results as soon as possible. Thanks

**Comment by probil** [comment]
@ivokun I've finished investigation and it's actually works. 
For example for event `chat message` it this way:
```js
mutations: {
  'SOCKET_CHAT MESSAGE'(state, payload){
      console.log('mutation');
  },
actions: {
    'socket_chatMessage'(){
      console.log('ACTION');
    }
}
```
So for your event `push ner data` it should work this way:
```js
mutations: {
  'SOCKET_PUSH NER DATA'(state, payload){
      console.log('mutation');
  },
actions: {
    'socket_pushNerData'(){
      console.log('ACTION');
    }
}
```
Let me know if that helped you or not.

I don't feel like it's the right way. I'm going to check the approach of converting events to actions and mutations soon.

**Comment by ivokun** [comment]
Yeah, you are right.
I can use it for my case, lol.

Sorry it seems i misunderstood the methods.
Thanks for your help Max!

**Comment by probil** [comment]
You are welcome, @ivokun 
It's not your fault, actully I've found methods misleading too. :thinking: 
Contact me if you have any other issues. Have a nice day!

**Comment by probil** [comment]
Also I've update docs so it should more clear for you
