### ISSUE TITLE
how to join rooms?

### ISSUE THREAD

**Issue by Black-Horse** [probil/vue-socket.io-extended#433]
Thanks for this awesome lib!

I am able to receive normal messages so far.
I want to join a certain room when the component loaded and then receive the messages for this room.

I tried variations of this but couldn't get it to work:
`    connect: function () {
      this.$socket.join('id-' + ${this.$route.params.id})
    }`
The server emits a message with a default name to this room. It seems like I cannot get the client to join this room, though.

Could you please give me advice on how to achieve this?

**Comment by capndave** [comment]
I could be wrong but I think the room joining needs to happen on the server side. Try emitting a `join` event (I used `this._vm.$socket.emit('join', 'my-app-name'` from vuex), then join that to the socket instance on the server.

**Comment by probil** [comment]
@capndave is right, rooms should managed on the backend. 

Anyway, this library just a small wrapper around `socket.io-client` which provides a bit more coherent integration with Vue.

Question it's not directly related to `vue-socket.io-extended`. I believe it's better to ping [socket.io community](https://socketio-slackin.herokuapp.com/) instead.
