### ISSUE TITLE
Nuxt socket io refetching data from server 

### ISSUE THREAD

**Issue by HunterJS-bit** [probil/vue-socket.io-extended#434]
Hi, guys, I'm trying to use your plugin with Nux as you explained here

https://github.com/probil/vue-socket.io-extended#mountain_bicyclist-usage-with-nuxtjs

But the issue I'm getting is that every time server is offline 
nuxtServerInit is called to fetch data again and again like in loop,,
could you please help with this problem ?

**Comment by probil** [comment]
Hi, @HunterJS-bit 

By default socket.io tries to reconnect until server is available and it's appropriate behaviour for a majority of cases. But you can control it by passing `reconnectionAttempts` or `reconnection` option to socket.io constructor.

```js
const socket = io('http://socketserver.com:1923', { reconnection: false }); // stop reconnecting after the first fail
// or
const socket = io('http://socketserver.com:1923', { reconnectionAttempts: 3 }); // stop reconnecting after the 3rd attempt 
```

Thanks for your issue 👍

**Comment by probil** [comment]
Please confirm that issue is resolved

**Comment by HunterJS-bit** [comment]
It resolved closing issue, thanx
