### ISSUE TITLE
How to refresh the browser cookie?

### ISSUE THREAD

**Issue by wnjustdoit** [probil/vue-socket.io-extended#436]
When I use the single web socket client, it connect just as the client page loaded. After that, the client cookies may be updated during the socket client alive. So my question is how to refresh cookies to the socket client, the it requests the backend with those newest cookies or something else of the browser?
One possible solution is:
`this.$socket.client.disconnect();
            this.$socket.client.connect();`
But when call disconnect method, the error occured like: [TypeError: this.$socket.$unsubscribe is not a function](https://github.com/probil/vue-socket.io-extended/issues/431)
Another possible solution is to create a new web socket client each time when the page is refreshed.

Look forward to your reply.

**Comment by probil** [comment]
Hey @wnjustdoit 
This plugins is only a small wrapper around `socket.io-client`, so you should probably ask your question in [`socket.io-client` community](https://socketio-slackin.herokuapp.com/) instead. It's quite an edge case I can tell you. 🤔 

If you you have any other `vue-socket.io-extended` questions I'll be glad to answer.
Thanks for your question anyway
Good luck 🍀
