### ISSUE TITLE
How to actually use namespaced vuex modules?

### ISSUE THREAD

**Issue by ArtyomPLAY** [probil/vue-socket.io-extended#438]
I'm using nuxt and cant really get how to make namespaced modules working. Is there more detailed docs out there?
Thanks

**Comment by probil** [comment]
@ArtyomPLAY It works the same way as with on vuex store without modules. 
If there is a mutation or action that matches an event it will be triggered no matter in which module it's defined.

Let's say you have an event called `new-message` triggered on the server. To catch the data in Vuex just create a mutation `SOCKET_NEW_MESSAGE` or action `socketNewMessage` in the vuex module which is the most appropriate for storing new message data.

I can create a working example for you but I don't have much time these days

**Comment by ArtyomPLAY** [comment]
@probil thx for the answer. At first i thought "namespaces" meant actual socket.io namespaces which we can create on the server with `const nsp = io.of('/my-namespace');` , so i couldnt figure out due to this misunderstood. Would be awesome if you add support for socket.io namespaces.

**Comment by probil** [comment]
there is a feature request for that #81
