### ISSUE TITLE
Events with spaces

### ISSUE THREAD

**Issue by Lambik** [probil/vue-socket.io-extended#443]
Hi,

I'm doing the socket.io tutorial, which has the event `chat message`. I've vue-ified the project, and used your library, however since I'm new to both socket and vue, I don't really know how to capture the spaced event name.

Your docs mention that in the vuex store there is something like "chat message	SOCKET_CHAT MESSAGE	socket_chatMessage", but since I don't know yet what vuex is, I'm using regular vue and use this structure:

		sockets: {
			connect() {
				console.log('socket connected')
			},
			chatMessage(msg) {
				alert('test1 ' + msg);
			},
			socket_chatMessage(msg) {
				alert('test2 ' + msg);
			}
		},

None of my alerts are triggered, but when I do the more basic javascript of:

    socket.on('chat message', function (msg) {
        alert('works: ' + msg)
    });

it works, so I must be naming my function incorrectly I guess? Are spaces supported on the regular vue object?

**Comment by yooneskh** [comment]
Test if this works
```
sockets: {
  'chat message'(msg) {
    console.log(msg);
  }
}

**Comment by Lambik** [comment]
Oh! I didn't know you could do that! This works, thanks :-)
