### ISSUE TITLE
Usage of non-API function breaks mock-socket compatibility

### ISSUE THREAD

**Issue by dan-sel** [probil/vue-socket.io-extended#454]
Currently, [Observe.js](https://github.com/probil/vue-socket.io-extended/blob/6cba52bd583f0050e7488075cf4288b96645eb92/src/Observe.js#L44) augments socket.io-client's [onevent](https://github.com/socketio/socket.io-client/blob/master/lib/socket.js#L268) function which is explicitly marked private.

This is not only risky because the private API may change in the future without notice, but it also means that this plugin is incompatible with any socket.io-client mocking library that correctly only mocks the public API, e.g. mock-socket.

**Comment by probil** [comment]
Hey @dan-sel 
This was conscious decision actually. `socket.io-client` doesn't provide official way to subscribe to all events. I'd use another way if it was available

**Comment by dan-sel** [comment]
Sorry for the late response. You don't need to subscribe to all events. All event names and handlers are known beforehand, so you can simply subscribe to each event separately. The socketio client already filters events by name and executes the subscribed handlers; there's no need to reimplement this functionality.
