### ISSUE TITLE
Able to connect & send message to the socket server, but unable to receive

### ISSUE THREAD

**Issue by zhzhang-4390** [probil/vue-socket.io-extended#455]
In my `App.vue`:

```
sockets: {
    connect() {
      this.$socket.client.emit("register", {
        user: this.$store.getters.getUser._id,
      });
    },

    message(data) {
      console.log("message");
    },
  },
```

In my server:

```
socket.to(existingSocket._id).emit("message", data);
```

Client side `connect()` & `emit()` have been tested and are working, server side `emit()` has executed. But I'm not receiving anything on the client side.

Is any of my syntax wrong or something is outdated?

**Comment by zhzhang-4390** [comment]
Sorry, it's my own bug.

**Comment by loongmxbt** [comment]
@zhzhang-4390 Hi, I've met the same problem. Would you please tell me how you solved this?
