### ISSUE TITLE
action socket not executed with VueX

### ISSUE THREAD

**Issue by tibztibz** [probil/vue-socket.io-extended#458]
hey,

I have a problem to execute my action socket with VueX.

Vue: "version": "2.6.11",
VueX: "version": "3.3.0", 
vue-socket.io-extended: "version": "4.0.1",

the socket server emits event 'response'.

Before, I used `this.$socket.$subscribe` on the event 'response' in the app component and it was  working but I don't know if it's normal, when I subscribe an other event in an other child component the event 'response' not working.
It's seems the listener on the event 'response' to be deleted...

So, I implemented my store with vue.socketio-extend just like the doc, but it's not working...

my main.js

```js
import Vue from 'vue'
import App from './App'

import router from './router'
import VueSocketIOExt from 'vue-socket.io-extended'
import timesupStore from './store/timesupStore'
import socketClient from './socket/socketClient'

import VueX from 'vuex'

Vue.config.productionTip = false

Vue.use(VueSocketIOExt, socketClient, { timesupStore })

new Vue({
  store: timesupStore,
  el: '#app',
  router,
  components: { App },
  template: '<App />',
})
```

my socketClient

```js
import io from "socket.io-client";

const socketClient = io('http://localhost:3000')

socketClient.on('connect', () => { console.log('socket connected')})
socketClient.on('disconnect', () => { console.log('socket disconnected')})

export default socketClient
```

The actions from my store:

```
export default {
  socket_response (store, socketResponse) {
    // execute mutations which don't have the prefix SOCKET_
  },
  // other actions....
}
```

Any help would be appreciated,

Thanks

**Comment by probil** [comment]
Hey @tibztibz 👋 
You haven't passed your store properly, try this instead:
```js
Vue.use(VueSocketIOExt, socketClient, { store: timesupStore }) 
```

**Comment by tibztibz** [comment]
@probil oh my god !! how i can't see that...
 it's ok, it's works, thanks !

but for the dynamic listener with $subscribe which seems delete the first listener, it's normal ?

**Comment by probil** [comment]
Nice 

> but for the dynamic listener with $subscribe which seems delete the first listener, it's normal ?

Could you explain a bit more? Anyway it's better to create a new issue for that 🤔

**Comment by tibztibz** [comment]
okey i close this one and open an other.

**Comment by tibztibz** [comment]
the new issue : https://github.com/probil/vue-socket.io-extended/issues/460
