### ISSUE TITLE
I can't listen multi event with this.$socket.$subscribe

### ISSUE THREAD

**Issue by tibztibz** [probil/vue-socket.io-extended#460]
Hello,

Vue: "version": "2.6.11",
VueX: "version": "3.3.0",
vue-socket.io-extended: "version": "4.0.1",

here's the probleme:

In my App component, I listened the event 'response' with this.$scoket.$subscribe in the created(), and in a child component, I listened an other event with  this.$scoket.$subscribe 'startChrono' in the created() of child component.

When I arrived in child component, my listener 'response' wasn't working.
It's seems the listener 'startChrono' remove the listener 'response'...

So, my question is : it's normal or not ?

**Comment by probil** [comment]
Hi @tibztibz 
I'm not sure to be honest 🤔 I need a codesandbox (you can for that one mentioned in README) or github repo with a reproduction of the issue.

BTW You can always setup listeners directly on the socket instance. `$subscribe` and `$unsubscribe` is just for convenience. I've haven't tested those methods profoundly TBH

**Comment by tibztibz** [comment]
Hi @probil ,

If you want more context, it's a timesup where players create a room, choose their team, create words, and when all player are ready, start the game.
When the first player starts the turn, I'm using the socket to start the chrono of all players.
In this case, I'm using the $subscribe to do that.

I'm also using the socket to share data between the different players of the room.
In this case, I'm using the implementation of vue-socket.ioExtends in the store.

If  you want more context, please check my code : 

the component Child 'Game' :  https://gitlab.com/thibaultledeux/timesupvuejs/-/blob/master/src/components/Game.vue

the store : https://gitlab.com/thibaultledeux/timesupvuejs/-/blob/master/src/store/timesupStore.js

thx a lot !

**Comment by probil** [comment]
Hey @tibztibz 
Thanks for your issue.
I've already responded you here: https://github.com/probil/vue-socket.io-extended/issues/461#issuecomment-636199685
Try to use socket instance directly instead
