### ISSUE TITLE
Is there a way to fully control URL?

### ISSUE THREAD

**Issue by axel-verse** [probil/vue-socket.io-extended#485]
I have no /socket.io in ws url, and I can not change this (I am frontend developer). So is there a way to change URL to my entry point?

**Comment by probil** [comment]
Hi, @axel-verse 
You can configure socket io instance however you like. There are a lot of configurations available including `path` which is `/socket.io` by default. 

I know Client API is not straightforward, but you can pass any option from here to the socket.io constructor.
https://socket.io/docs/client-api/#new-Manager-url-options

So here is potential version of your code:
```js
import VueSocketIO from 'vue-socket.io-extended';
import io from 'socket.io-client';

const socket = io('http://your-socket-server.com:1923', {
  path: '/custom-path-here', // <---
});

Vue.use(VueSocketIO, socket);

**Comment by probil** [comment]
I will reopen the issue if that won't help

**Comment by axel-verse** [comment]
Thanks a lot, i tried this and it's working as expected :)

**Comment by probil** [comment]
Nice to hear that @axel-verse 
Have a great day!
