### ISSUE TITLE
How to change default namespace?

### ISSUE THREAD

**Issue by denisvitez** [probil/vue-socket.io-extended#512]
I am using this library to communicate with Flask server, and by debugging I found out that this library uses a namespace of `/socket.io`. So message won't go through when this namespace is not matched on the server. Is there a possibility to define a different namespace when initializing the connection? If so, this could maybe be added to documentation :)

I am currently using version `4.0.6`

**Comment by probil** [comment]
Hi @denisvitez 👋 
The library just uses socket io instance you are passing. Hence, just configure it:

```js
import VueSocketIOExt from 'vue-socket.io-extended';
import { io } from 'socket.io-client';

const socket = io('http://localhost/admin', {  path: '/mypath' });  // path is `/socket.io` by default

Vue.use(VueSocketIOExt, socket);
```

https://socket.io/docs/v2/client-api/#new-Manager-url-options

but keep in mind that there a new version of `socket.io-client` v3 which uses a bit different configuration. Check the docs of socket.io for your version.

**Comment by denisvitez** [comment]
Hey, 

thank you for the information. I also noticed that
`const socket = io('http://localhost', {  path: '/mypath' });`
and
`const socket = io('http://localhost/mypath');`

Work in the same way, so the namespace part is just the URL path. Didn't know that, I'm fairly new to Socket.IO. Since I got all the information that I needed and my app is working now, I will close this issue.

**Comment by probil** [comment]
@denisvitez Good to know. Didn't know that too
