### ISSUE TITLE
Does not receive any events

### ISSUE THREAD

**Issue by AllanOricil** [probil/vue-socket.io-extended#515]
I tried the old lib, then switched to yours and I had no lucky. 
Here is my main.js

The code below is the only way I made it """"work""". When I used the import like you wrote in the README for the socket.io-client it was throwing an exception saying io is not an object. I just changed from `import `{ io } from 'socket.io-client';` to `import io from 'socket.io-client';`

````js
import Vue from 'vue';
import VueSocketIOExt from 'vue-socket.io-extended';
import io from 'socket.io-client';

const socketInstance = io(`${process.env.SERVER_URI}`, {
  transports: ['websocket'],
});
Vue.use(VueSocketIOExt, socketInstance);
````

here is the component. 
````html
<template>
 <div></div>
</template>
<script>
import { mapState, mapActions, mapMutations } from 'vuex';
import Loading from '@/components/loading';
export default {
    name: 'App',
    components: {
        Loading
    },
    data: ()=>{
        return {
            loading : true
        }
    },
    created(){
        this.fetchEnvironments();
        this.fetchConfiguration();
        this.fetchDefaultusername().then(() => this.loading = false);
    },
    sockets: {
        connect() {
            console.log('socket connected')
        },
        testMessage(val) {
            console.log('this method was fired by the socket server. eg: io.emit("customEmit", data)');
            console.log(val);
        }
    },
    beforeMount(){
        window.vscode.onReceiveSalesforceDefaultusername((message) => {
            this.setSalesforceDefaultusername(message.data);
        });
    },
    computed:{
        ...mapState({
            configuration: state => state.user.configuration
        })
    },
    methods:{
        ...mapActions({
            fetchEnvironments: 'salesforce/fetchEnvironments',
            fetchDefaultusername: 'salesforce/fetchDefaultusername',
            fetchConfiguration: 'user/fetchConfiguration'
        }),
        ...mapMutations({
            setSalesforceDefaultusername: 'salesforce/setSalesforceDefaultusername'
        })
    }
}
</script></style>

````

I see on the network tab socket events. But they are empty and with status code 101. And on my server the `ìo.on('connect') ` and `ìo.on('connection')` don't work
![image](https://user-images.githubusercontent.com/55927613/106340354-66d5ce00-6291-11eb-8578-d8b617117a3f.png)

This is my server

`````js
const dotenv = require('dotenv');
const express = require("express");
const morganBody = require("morgan-body");
const bodyParser = require("body-parser");
const cors = require('cors');
const { configurationProperties } = require('../soqlEditor/configurationProperties');


if(process.env.NODE_ENV !== 'production'){ 
    dotenv.config();
}

const app = express();
app.use(cors());
app.use(bodyParser.json({ type: "application/vnd.api+json" }));
app.use(bodyParser.json({ type: "application/json" }));
morganBody(app);

const http = require('http').Server(app);
const io = require('socket.io')(http, {
    cors: {
        origins: 'vscode-webview://*'
    }
});
io.on('connect', () => {
    console.log('connected');
});
app.set('io', io);

http.listen(process.env.PORT || 5000, 'localhost', () => {
    const { address, port } = http.address();
    console.log(`Listening at http://${address}:${port}`);    
});
````

**Comment by probil** [comment]
Hey @AllanOricil 
I assume you are using socket.io v3 which is not support.

- v2 has been around for several years and is stable for vast majority of users and use cases. 
- v3 was released few months ago and has brought a few breaking changes  which are not compatible with the library just yet

So if you don't need socket.io v3 features, I recommend sticking to v2. It can be installed this way:
```bash
npm i socket.io-client@v2-latest
```

You don't have to rollback server-side library thought. It has v2 compatibility mode which can be enabled with a flag (check socket.io docs)

V3 support is my top priority right now and it's going to be released soon. Let me know whether rollback helped. Probably I need to update the docs

**Comment by AllanOricil** [comment]
@probil I updated my dependency to include the v2-latest package version like you suggested and it still not working. 

````json
"dependencies": {
    "@allanoricil/sql-formatter": "^0.1.0",
    "@nuxtjs/axios": "^5.12.5",
    "bootstrap": "^4.6.0",
    "bootstrap-vue": "^2.20.1",
    "core-js": "^3.8.3",
    "nuxt": "^2.14.12",
    "object-hash": "^2.1.1",
    "socket.io-client": "^2.4.0",
    "soql-parser-js": "^3.0.0",
    "v-clipboard": "^2.2.3",
    "vue-codemirror": "^4.0.6",
    "vue-confirm-dialog": "^1.0.2",
    "vue-drag-drop": "^1.1.4",
    "vue-highlightjs": "^1.3.3",
    "vue-inline-svg": "^2.0.0",
    "vue-json-pretty": "^1.7.1",
    "vue-json-viewer": "^2.2.17",
    "vue-loading-spinner": "^1.0.11",
    "vue-multiselect": "^2.1.6",
    "vue-shortkey": "^3.1.7",
    "vue-socket.io-extended": "^4.0.6",
    "vue-stripe-checkout": "^3.5.14-beta.0",
    "vue-stripe-elements-plus": "^0.3.2",
    "vuelidate": "^0.7.5"
  },
````

This is how I configured the plugin in Nuxt

````js
import Vue from 'vue'
import io from 'socket.io-client'
import VueSocketIOExt from 'vue-socket.io-extended'

const socketInstance = io(`${process.env.SERVER_URI}`, {
  transports: ['websocket'],
})

Vue.use(VueSocketIOExt, socketInstance)

````

And inside my component I added two socket events using ``sockets` prop. It does not thrown any errors, in the Network tab I can see websocket 101 events but none of the `console.log` messages appear. My server also is not seen the connection and i don't really know the reason.

````js
sockets: {
    connect(){
      console.log('connected');
    },
    testMessage(){
      console.log('test Message');
    }
  },
````

**Comment by AllanOricil** [comment]
@probil  I finally found out the problem. I was using v3 on my server. Now both are v2 and it is working as expected. Thank you anyway. Please, update the documentation to leave it clear that people should use v2 2.4.1 in the client and v2.4.0 in the server. Also, in the server, because it is v2, they have to configure it like so if they are using it with express:


````js
require('socket.io')(server, { serveClient: false });
````

It is necessary to not allow socket io to load the client stuff.
