### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by geomen888** [probil/vue-socket.io-extended#52]
Hi, pls provide typings initialization for typescript something like
```bash
npm install @types/vue-socket.io-extended
```
thank U

**Comment by probil** [comment]
I don't use TypeScript personally, but I will check what I can do.

**Comment by probil** [comment]
PR is welcome if someone can provide valid typings. I don't have much time for that right now

**Comment by probil** [comment]
@andreagottsponer I'm not good at TypeScript and I need you suggestion.
Will it work if I create this file inside root directory of `vue-socket.io-extended` project?
Maybe it should be called `index.d.ts`?
Do I need to add everything to `package.json`?

**Comment by TotomInc** [comment]
There have been a lot of work done in the commit f7312d31e7ffb0d24630529d6af9756c3b171215. I've tested the branch locally and it works fine beside a few tweaks needed (I've explained everything in the commit).
