### ISSUE TITLE
Support socket.io v4

### ISSUE THREAD

**Issue by kmalski** [probil/vue-socket.io-extended#536]
Hi, is there possibility to add support for socket.io v4? I tried to simply use **vue-socket.io-extended** with **socket.io-client** v4 and it doesn't work out of the box.

**Comment by probil** [comment]
Hi @kmalski 👋 
It's all about compatibility. It should work if you use socket.io v4 **on your server**. Versions of the client and server should match. 

[There is a working example here](https://github.com/probil/vue-socket.io-extended/tree/master/examples/simple-chat) built on socket.io-client and server v4

Let me know whether it helped. Have a nice day

**Comment by kmalski** [comment]
Hi @probil
Thank you for the advice. During the migration from socket.io **v2** to **v3** I missed the part about new default cors options. Now everything is working correctly. 

Thank you once again 😃
