### ISSUE TITLE
Multiple Socket Namespaces 

### ISSUE THREAD

**Issue by abdulhadi-lababidi** [probil/vue-socket.io-extended#538]
In my project, the backend has multiple socket namespaces, let say:

- /app1/module_1
- /app1/module_2
- /app2/module_1
... etc.
so if I tried to to this

`const socketApp1Module1 = io('/app1/module_1');`
`const socketApp1Module2 = io('/app1/module_2');`
`const socketApp2Module1 = io('/app1/module_1');`
`Vue.use(VueSocketIOExt, ?What should I pass here?);`

and on the same page I might have a use case that would require me to connect and receive events from **multiple namespaces**
and the events from different namespaces may conflict with each other

so any suggestion how to achieve that using this cool library?

**Comment by probil** [comment]
Hi @abdulhadi-lababidi 

Unfortunately multiple namespaces aren't supported at the moment. Closing because it's duplication of #81
