### ISSUE TITLE
Socket connect not triggering from Vue to Nodejs backend!

### ISSUE THREAD

**Issue by harishankards** [probil/vue-socket.io-extended#65]
Hi,

I was very worried about the vue-socket.io as it seems to unmaintained. And you come for the rescue. Thanks a lot for this.

In my project, I'm using node.js for backend API running at `localhost:3000` and Vue for frontend running at `localhost:8080`. I have added the basic socket code to print console on connecting. But it's not working.

Below is my code

Node backend: `app.js`
```js
const http = require('http');
const io = require('socket.io')(http);

io.on('connection', function(socket){
  console.log('An user connected');
});
```

and Vue frontend: `main.js`
```js
import VueSocketio from 'vue-socket.io-extended'
import io from 'socket.io-client'

Vue.use(VueSocketio, io('http://socketserver.com:1923'))


new Vue({
  el: '#app',
  router,
  store,
  template: '<App/>',
  components: { App },
  sockets: {
    connect () {
      console.log('socket connected')
    },
    customEmit (val) {
      console.log('this method was fired by the socket server. eg: io.emit("customEmit", data)', val)
    }
  },
  methods: {
    clickButton (val) {
      // this.$socket is `socket.io-client` instance
      this.$socket.emit('emit_method', val)
    }
  }
})
```

What am I doing wrong?

**Comment by probil** [comment]
You are welcome, @harishankards. I'm glad to help :)

About your question, I think this line is not correct:
```js
Vue.use(VueSocketio, io('http://socketserver.com:1923'));
```
In docs, `http://socketserver.com:1923` is used just to show the main idea and you should replace it with the actual address of your socket server. So, replace it with:
```js
Vue.use(VueSocketio, io('http://localhost:3000'));
```
And it should work. 

Let me know if that helped you.

**Comment by harishankards** [comment]
That worked. Thanks @probil
